Allow extra args to be passed to the test script via NPM

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -2,5 +2,11 @@
 
 ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 
-cd "$ROOT_DIR" || exit
+cd "$ROOT_DIR" || exit 1
 ./node_modules/.bin/wdio wdio.conf.js "$@"
+
+if [ $? -eq 0 ]; then
+  echo "Tests failed!"
+fi
+
+exit 0
